version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    cooldown:
      default-days: 3
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
        - "*"

  - package-ecosystem: uv
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
        - "*"
